In [1]:
#Calculating Dot Product

import numpy as np

# Create two vectors
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])

# Calculate dot product
np.dot(vector_a, vector_b)

np.int64(32)

In [3]:
# Adding and Subtracting Matrices

import numpy as np

# Create matrix
matrix_a = np.array([[1, 1, 1],
                     [1, 1, 1],
                     [1, 1, 2]])

# Create matrix
matrix_b = np.array([[1, 3, 1],
                     [1, 3, 1],
                     [1, 3, 8]])

# Add two matrices
print(np.add(matrix_a, matrix_b))

# Subtract two matrices
print(np.subtract(matrix_a, matrix_b))

[[ 2  4  2]
 [ 2  4  2]
 [ 2  4 10]]
[[ 0 -2  0]
 [ 0 -2  0]
 [ 0 -2 -6]]


In [6]:
#Mulptplying Matrices

import numpy as np

matrix_a = np.array([[1,1],
                   [1,2]])

matrix_b = np.array([[1,3],
                   [1,2]])

np.dot(matrix_a,matrix_b)

array([[2, 5],
       [3, 7]])

In [7]:
# Inverting a Matrix

import numpy as np

matrix = np.array([[1,4],
                   [2,5]])

np.linalg.inv(matrix)

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

In [12]:
# Generating Random Values

import numpy as np

np.random.seed(0)
print(np.random.random(3))

# Generate three random integers between 1 and 10
print(np.random.randint(0, 11, 3))

# Draw three numbers greater than or equal to 1.0 and less than 2.0
print(np.random.uniform(1.0, 2.0, 3))

[0.5488135  0.71518937 0.60276338]
[3 7 9]
[1.6235637  1.38438171 1.29753461]
