In [100]:
import numpy as np
arr=np.array([1,2])
np.zeros(arr)
np.ones(arr)

array([[1., 1.]])

In [48]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(np.sum(arr))
print(np.mean(arr))
print(np.min(arr))
print(np.max(arr))

150
30.0
10
50


In [56]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr[-2])

40


In [66]:
#slicing[start:stop:step]
import numpy as np
arr=np.array([10,20,30,40,50,60])
print(arr[1:5])
print(arr[:4])
print(arr[::2])
print(arr[::-1])

[20 30 40 50]
[10 20 30 40]
[10 30 50]
[60 50 40 30 20 10]


In [70]:
#fancy indexing-slecting multiple element at once
import numpy as np
arr=np.array([10,20,30,40,50,60])
print(arr[[0,2,4]])

[10 30 50]


In [76]:
#flitering(Boolean Masking)
import numpy as np
arr=np.array([10,20,30,40,50,60])
print(arr[arr>25])

[30 40 50 60]


In [80]:
#reshaping and manipulating arrays 
"""Syantax : reshape(row,coloumn) specify new shape
if dimension match"""
  
import numpy as np
arr=np.array([1,2,3,4,5,6])
re_shape=arr.reshape(2,3)
re_shape

array([[1, 2, 3],
       [4, 5, 6]])

In [82]:
""".ravel() -> view
.flatten() -> copy"""

import numpy as np
arr=np.array([[1,2,3],[5,6,7]])
print(arr.ravel())
print(arr.flatten())

[1 2 3 5 6 7]
[1 2 3 5 6 7]


In [106]:
#Advanced numpy
"""
np.insert(array,index,value,axis=None)
"""
import numpy as np
arr=np.array([10,20,30,40,50,60])
print(arr)
new_arr=np.insert(arr,2,18)
new_arr

[10 20 30 40 50 60]


array([10, 20, 18, 30, 40, 50, 60])

In [124]:
import numpy as np
arr=np.array([[1,2],[3,4]])
new_arr=np.insert(arr,1,[5,6],axis=1)
new_arr

array([[1, 5, 2],
       [3, 6, 4]])

In [130]:
"""
np.append()
"""
import numpy as np
arr=np.array([10,20,30,40,50,60])
new_arr=np.append(arr,70)
new_arr

array([10, 20, 30, 40, 50, 60, 70])

In [140]:
"""
np.concatenate({array1,array2,axis=0})
axis=0 -> vertical stacking
axis=1 -> Horizanatal stacking
"""
import numpy as np
arr_1=np.array([1,2,3])
arr_2=np.array([4,5,6])
new_arr=np.concatenate((arr_1,arr_2))
new_arr

array([1, 2, 3, 4, 5, 6])

In [148]:
"""
np.delete(array,index,axis=None)
"""
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr)
new_arr=np.delete(arr,1)
new_arr

[10 20 30 40 50]


array([10, 30, 40, 50])

In [168]:
import numpy as np
arr=np.array([[1,2],
             [3,4],
             [5,6]])
print(arr)
new_arr=np.delete(arr,1,axis=0)
new_arr

[[1 2]
 [3 4]
 [5 6]]


array([[1, 2],
       [5, 6]])

In [170]:
"""
vstack(),hstack()
"""
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print(np.vstack((arr1, arr2)))
print(np.hstack((arr1, arr2)))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [172]:
"""
np.split() -> equal
np.hsplit() ,np.vsplit()
"""
import numpy as np
arr=np.array([10,20,30,40,50,60])
print(np.split(arr,3))

[array([10, 20]), array([30, 40]), array([50, 60])]


In [1]:
#Boardcasting : Withoout using loops,simple  and vectorization
import numpy as np
prices=np.array([100,200,300])
discount=10
final_prices=prices-(prices*discount/100)
print(final_prices)

[ 90. 180. 270.]


In [3]:
import numpy as np
matrix=np.array([[1,2,3],[5,6,7]])
vector=np.array([10,20,30])
result=matrix+vector
result

array([[11, 22, 33],
       [15, 26, 37]])

In [15]:
list1 = [1,2,3]
list2 = [4,5,6]

result=[x+y for x,y in zip(list1,list2)]
result

[5, 7, 9]

In [17]:
#Fast Vectorizer
import numpy as np

arr1=np.array([1,2,3])
arr2=np.array([1,2,3])

result=arr1+arr2
result

array([2, 4, 6])

In [21]:
#Handling missing values
"""
1) np.isnan(array) -> datect missing value 
2) np.nan_to_num(array,nan=value) ->replace no
3) np.isinf()
"""
import numpy as np
arr=np.array([1,2,np.nan,4,np.nan])
print(np.isnan(arr))
print(np.nan==np.nan)

[False False  True False  True]
False


In [27]:
import numpy as np
arr=np.array([1,2,np.nan,4,np.nan])
new_arr=np.nan_to_num(arr,nan=100)
new_arr

array([  1.,   2., 100.,   4., 100.])

In [29]:
import numpy as np
arr=np.array([1,2,np.inf,4,-np.inf])
print(np.isinf(arr))

[False False  True False  True]
